### ISSUE TITLE
Integer column has NA values in column

### ISSUE THREAD

**Issue by gregoriopellegrino** [jbn/pandas_access#18]
Ciao,
sto usando il pacchetto per caricare una tabella di un database di Access, ma ricevo l'errore:

```
Traceback (most recent call last):
  File "mail.py", line 28, in <module>
    test = mdb.read_table(db_file, "test")
  File "/usr/local/lib/python3.10/site-packages/pandas_access/__init__.py", line 127, in read_table
    return pd.read_csv(proc.stdout, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1187, in pandas._libs.parsers.TextReader._convert_with_dtype
ValueError: Integer column has NA values in column 40
```

**Comment by saschaishikawa** [comment]
Try this: `mdb.read_table(db_file, "test", converters_from_schema=False)`

**Comment by jakubsatka** [comment]
@saschaishikawa that saved me. Thank you!
